name: Convert README to PDF

on:
  push:
    branches:
      - main  # Runs on every push to the main branch
  workflow_dispatch:  # Allows manual runs from GitHub Actions

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert README to PDF
        run: pandoc README.md -o README.pdf --pdf-engine=wkhtmltopdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: README_PDF
          path: README.pdf
